version: '3.1'
services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
      - ./conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build: ./conf/php
    volumes:
      - ./www:/var/www/html
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
    links:
      - mysql
  mysql:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: tilesdb
      MYSQL_ROOT_PASSWORD: p4ssw0rd!

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: p4ssw0rd!