version: '3.1'
services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
      - ./src:/var/www/html/wp-content/plugins/tiles-for-wordpress
      - ./conf/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./conf/php
    ports:
      - "9000:9000"
    volumes:
      - ./www:/var/www/html
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    ports:
      - 3306:3306